# Generated by Django 4.1.3 on 2022-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=120)),
                ('zone', models.CharField(max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=9)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
