# Generated by Django 4.1.3 on 2022-11-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abs.zone'),
        ),
    ]
