# Generated by Django 4.1.3 on 2022-11-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0002_zone_alter_client_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
