# Generated by Django 4.1.3 on 2022-12-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0004_order_productqty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductQty',
            new_name='OrderItem',
        ),
    ]
